#!/bin/bash
# Auto-generated by Claude for the Tudget TestFlight ship (Part A: local build).
# Run this once from Terminal:  cd ~/tudget/ios && ./ship_part_a.sh
set -o pipefail
cd "$(dirname "$0")"

LOG="build_log.txt"
: > "$LOG"
log() { echo "$(date '+%H:%M:%S') $*" | tee -a "$LOG"; }

log "=== STEP 1: Xcode / CLT check ==="
xcode-select -p 2>&1 | tee -a "$LOG"
xcodebuild -version 2>&1 | tee -a "$LOG"

log "=== STEP 2: XcodeGen ==="
if ! command -v xcodegen >/dev/null 2>&1; then
  log "xcodegen not found, installing via Homebrew..."
  brew install xcodegen 2>&1 | tee -a "$LOG"
else
  log "xcodegen already installed: $(xcodegen --version 2>&1)"
fi

log "=== STEP 3: xcodegen generate ==="
xcodegen generate 2>&1 | tee -a "$LOG"
GEN_STATUS=${PIPESTATUS[0]}
log "xcodegen generate exit status: $GEN_STATUS"

log "=== STEP 4: Build to 'Any iOS Device (arm64)' (registers bundle ID + App Group) ==="
xcodebuild build -project Tudget.xcodeproj -scheme Tudget \
  -destination 'generic/platform=iOS' \
  -allowProvisioningUpdates 2>&1 | tee -a "$LOG"
BUILD_STATUS=${PIPESTATUS[0]}
log "Build exit status: $BUILD_STATUS"

log "=== STEP 5: Run test suite (iPhone 17 Pro simulator) ==="
xcodebuild test -project Tudget.xcodeproj -scheme Tudget \
  -destination 'platform=iOS Simulator,name=iPhone 17 Pro' 2>&1 | tee -a "$LOG"
TEST_STATUS=${PIPESTATUS[0]}
log "Test exit status: $TEST_STATUS"

log "=== STEP 6: Archive for distribution (Release) ==="
mkdir -p build
xcodebuild archive -project Tudget.xcodeproj -scheme Tudget \
  -configuration Release -archivePath build/Tudget.xcarchive \
  -destination 'generic/platform=iOS' \
  -allowProvisioningUpdates 2>&1 | tee -a "$LOG"
ARCHIVE_STATUS=${PIPESTATUS[0]}
log "Archive exit status: $ARCHIVE_STATUS"

log "=== SUMMARY ==="
log "generate=$GEN_STATUS build=$BUILD_STATUS test=$TEST_STATUS archive=$ARCHIVE_STATUS"
if [ "$GEN_STATUS" -eq 0 ] && [ "$BUILD_STATUS" -eq 0 ] && [ "$TEST_STATUS" -eq 0 ] && [ "$ARCHIVE_STATUS" -eq 0 ]; then
  log "ALL STEPS SUCCEEDED. Archive at: $(pwd)/build/Tudget.xcarchive"
else
  log "ONE OR MORE STEPS FAILED. Check the output above for details."
fi
